### ISSUE TITLE
Migrate from tRPC v9 to v10

### ISSUE THREAD

**Issue by AyanavaKarmakar** [nexxeln/guestbook-blog#1]
The blog is handy for newcomers to get a quick introduction to the T3 Stack. However, it currently uses tRPC v9. As of now, tRPC v10 is out and ready for production according to the [docs](https://trpc.io/docs/v10/migrate-from-v9-to-v10). <br />
I am wondering if migrating to v10 is on the roadmap or not for both the code snippets on the blog and the demo site. I believe it would be helpful for newcomers to get introduced to v10 as well. Perhaps, a combination of v9 and v10 code snippets can be added/edited to the existing blog. Just my two cents. <br />
I would be more than happy to help if needed :)

**Comment by nexxeln** [comment]
Hey, I just don't have time to update the blog so I just added a warning at the top. If you would be willing to rewrite the blog and the code (will be a lot of work and I will nitpick a lot) then feel free to make a PR here and on https://github.com/nexxeln/nexxel.dev
