### ISSUE TITLE
tRPC v9 to V10 update

### ISSUE THREAD

**Issue by semsion** [nexxeln/guestbook-blog#4]
Many thanks @AyanavaKarmakar for the update of tRPC v9 to V10.

It appears as though both the guestbook application and the library itself is updated in the series of commits on the 21st of October. 

Looking at package.json where the versions have been updated, would we also need to run `npm install` to update dependencies, and or the package.lock file?

**Comment by AyanavaKarmakar** [comment]
Hey, @semsion! I just ran the installation [snippet](https://trpc.io/docs/v10/quickstart#installation-snippets) for tRPC v10, and it made the changes to the `package.json`, and `pnpm-lock.yaml` files.

**Comment by semsion** [comment]
Great, will do the same, will run the npm installation snippet then make similar modifications to the code.

Thanks for sharing!

**Comment by semsion** [comment]
After finally getting around to having a go at updating the project locally, wanted to add this to the response, in case others are having issues trying to update their previous project from v9. 

As the original project was set up with npm (npx) a rather scenic route had to be taken in order to get the dependencies updated. 
This is because running the (npm) installation snippet from the tRPC quickstart page was throwing a bunch of dependency errors. 
Looking at the latest repository version here, it looks like pnpm has been utilised (which upon rereading is clearer from an earlier comment); so in order for the dependency updates to take from package.json, a migration from npm to pnpm was performed via this guide https://dev.to/andreychernykh/yarn-npm-to-pnpm-migration-guide-2n04 

A peer dependency issue with @trpc/react@9.27.2 against @trpc/server@10.0.0-proxy-beta.24 and @trpc/client@10.0.0-proxy-beta.24 is still being flagged with pnpm, but as a warning, and not an error as it was with npm.

During the migration the previous package.json file was left in place, and then once this was complete, copying the contents of the latest repository package.json here over the top of the previous, and then doing a 'pnpm i' appeared to be the most fluid approach, as trying to run the 'pnpm add' command from the installation snippet was throwing an error.
